version: "3.1"
networks:
  elasticportalnetwork:
services:
  web:
    image: nginx:stable-alpine
    container_name: webserver
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - elasticportalnetwork
    container_name: ElasticPortal
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - elasticportalnetwork
    container_name: elastic_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
