<?php
return [
    'meta_keys' => [
        'newspapers' => 'ATTRIBUTES.METADATA.PUBDATA.PAPER.NEWSPAPERS',
        'pageref' => 'ATTRIBUTES.METADATA.PUBDATA.PAPER.PAGEREFERENCE',
        'docauthor' => 'ATTRIBUTES.METADATA.GENERAL.DOCAUTHOR',
        'date_created' => 'ATTRIBUTES.METADATA.GENERAL.DATE_CREATED',
        'category' => 'ATTRIBUTES.METADATA.GENERAL.CATEGORY',
        'section' => 'ATTRIBUTES.METADATA.PUBDATA.PAPER.SECTION',
        'date_publication' => 'ATTRIBUTES.METADATA.PUBDATA.PAPER.DATEPUBLICATION',
        'publication' => 'ATTRIBUTES.METADATA.PUBDATA.PAPER.PRODUCT',
        'docauthor' => 'ATTRIBUTES.METADATA.GENERAL.DOCAUTHOR',
        'imageauthor' => 'SYSATTRIBUTES.PROPS.IMAGEINFO.DOCUMENTINFO.AUTHOR',
        'doctype' => 'ATTRIBUTES.METADATA.GENERAL.DOCTYPE',
        'dockeyword' => 'ATTRIBUTES.METADATA.GENERAL.DOCKEYWORD',
        'doctitle' => 'ATTRIBUTES.METADATA.GENERAL.DOCTITLE',
        'path' => 'SYSTEM.ALERTPATH'
    ]
];
?>